### ISSUE TITLE
Pkg vignette using martins content 

### ISSUE THREAD

**Issue by sckott** [ropensci/rdatacite#12]
from https://github.com/datacite/metadata-reports

@mfenner

**Comment by mfenner** [comment]
Cool. BTW, will write blog post about `metadata-reports` today.

**Comment by sckott** [comment]
great, looking forward

**Comment by sckott** [comment]
- https://github.com/datacite/metadata-reports/blob/master/orcid/index.Rmd
- https://github.com/datacite/metadata-reports/blob/master/datacenters/index.Rmd
- https://github.com/datacite/metadata-reports/blob/master/overview/index.Rmd
