### ISSUE TITLE
rows = 10000 should not convert to 1e+5

### ISSUE THREAD

**Issue by benmarwick** [ropensci/rdatacite#15]
When I run:

```
dc_arch <- dc_search(q = "archaeology", rows = 100000)
```

I get:

```
https://search.datacite.org/api?q=archaeology&rows=1e+05&wt=json
Error: 500 - For input string: "1e+05"
```

But when I use this URL in my browser: https://search.datacite.org/api?q=archaeology&rows=100000&wt=json I appear to get a valid response.

So is it possible to protect large numbers to prevent the `dc_*` functions from getting a URL with exponential notation? I'm currently doing this, which seems to work:

```
dc_arch <- dc_search(q = "archaeology", rows = pretty(100000)[2])
```

But maybe there's a better way? Thanks!

**Comment by sckott** [comment]
thanks @benmarwick 

yep, need to make sure sci notation monster doesn't eat up large numbers - have done this in other pkgs, will have a look and see how i've done it before

**Comment by sckott** [comment]
@benmarwick try reinstalling - fix in `solrium` - `devtools::install_github("ropensci/rdatacite")` - which will  pull in newer `solrium`

**Comment by benmarwick** [comment]
Yes, thanks very much, that's fixed it!

**Comment by sckott** [comment]
great, glad it worked
