### ISSUE TITLE
Is language as a filter, usable in dc_works() ?

### ISSUE THREAD

**Issue by rossmounce** [ropensci/rdatacite#17]
I couldn't work out how to do it.

Would like to recreate this search (for English language theses) with rdatacite:
https://search.datacite.org/ui?q=resourceType%3AThesis&fq=&fq=&fq=&fq=&fq=language_facet%3A%22English%22&fq=

**Comment by sckott** [comment]
thx @rossmounce 

does this not do what you want: 

```r
dc_search(q = "resourceType:Thesis", fq='language_facet:"English"')
```

**Comment by rossmounce** [comment]
yes! thanks.

for some reason i thought I had to use ```dc_works``` not ```dc_search``` but that makes a lot more sense now. 

The use case is really interesting btw (imo). There's a whole load of journal articles hiding out in full-text available theses. We just need more granular metadata to associate phd thesis X (DOI) with papers Y & Z (DOI,DOI), theses where the author has an orcid supplied even more helpful. Exploring...

**Comment by sckott** [comment]
Cool use case.  Hmmm, hope you make some progress on that.
