### ISSUE TITLE
Stats API

### ISSUE THREAD

**Issue by sckott** [ropensci/rdatacite#7]
http://stats.datacite.org/

**Comment by sckott** [comment]
@mfenner is there an API for Datacite stats ?  I remember there being one, but can't find it now

**Comment by mfenner** [comment]
This is exactly the same API, only resolution stats are not included. Relevant example code is around here: https://github.com/datacite/stats-portal/tree/master/static/js/stats

**Comment by sckott** [comment]
> This is exactly the same API,

as what? you mean the solr API at http://search.datacite.org/api ?

**Comment by mfenner** [comment]
Sorry, yes the Solr API that you are already supporting.

**Comment by sckott** [comment]
ok, thx
